// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STIMario.Models;

namespace STIMario.Migrations
{
    [DbContext(typeof(STIMarioContext))]
    partial class STIMarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("STIMario.Models.ejercicios", b =>
                {
                    b.Property<int>("IDejercicio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEjercicio");

                    b.Property<int>("puntaje");

                    b.HasKey("IDejercicio");

                    b.ToTable("ejercicios");
                });

            modelBuilder.Entity("STIMario.Models.resultados", b =>
                {
                    b.Property<int>("IDresultados")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("respuestasCorrectas");

                    b.Property<int>("respuestasIncorrectas");

                    b.HasKey("IDresultados");

                    b.ToTable("resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
